echo "Setting up Android SDK..."

# 清除已有的 SDK 安装并重新安装
rm -rf $HOME/Android/Sdk
mkdir -p $HOME/Android/Sdk

# 下载并解压 SDK
curl -sL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o android-tools.zip
unzip android-tools.zip -d $HOME/Android/Sdk
rm android-tools.zip

# 配置环境变量
echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

# 调试输出
echo "Current PATH: $PATH"
ls -la $ANDROID_HOME  # 输出 SDK 目录结构
which sdkmanager  # 确认 sdkmanager 是否存在

# 接受许可协议
yes | sdkmanager --licenses

# 安装 SDK 组件
sdkmanager --update -v --verbose || (sleep 5 && sdkmanager --update -v --verbose)
sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "platform-tools"
