      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK..."
          
          # 清除已有的 SDK 安装并重新安装
          rm -rf $HOME/Android/Sdk
          mkdir -p $HOME/Android/Sdk

          # 下载并解压 SDK
          curl -sL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o android-tools.zip
          unzip android-tools.zip -d $HOME/Android/Sdk
          rm android-tools.zip

          # 配置环境变量
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

          # 输出当前 PATH 和 SDK 目录结构，调试用
          echo "Current PATH: $PATH"
          ls -la $ANDROID_HOME  # 输出 SDK 目录结构

          # 确保 sdkmanager 可用
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          which sdkmanager  # 确认 sdkmanager 是否存在

          # 安装 SDK 组件，手动指定组件版本
          sdkmanager --update -v
          sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "platform-tools"
