name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            python3-pip \
            openjdk-17-jdk \
            unzip \
            zip \
            libncurses5

          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Create virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || true  # 如果你没有 requirements.txt 可以删掉这行

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: kivy-app-debug-apk
          path: bin/*.apk
