jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk

    - name: Install buildozer and dependencies
      run: |
        pip install buildozer
        sudo apt install -y python3-pip build-essential libssl-dev libffi-dev \
          python3-dev libxml2-dev libxslt1-dev zlib1g-dev

    - name: Install Android SDK & NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

    - name: Set environment variables
      run: |
        echo "export ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/23.1.7779620" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug
