name: Build and Upload EXE to Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile speakers.py

      - name: Move EXE to artifacts folder
        run: |
          mkdir artifacts
          move dist\speakers.exe artifacts\speakers.exe

      - name: Commit and push EXE back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add artifacts/speakers.exe
          git commit -m "Add built EXE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
