name: Build TTS Application (EXE)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      # Step 4: Build the EXE with PyInstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed speakers.py  # 打包为单个 EXE 文件

      # Step 5: Upload the EXE as an artifact
      - name: Upload EXE as artifact
        with:
          name: tts-app
          path: dist/tts_script.exe
